In [1]:
import numpy as np

# DataTypes & Attributes

In [2]:
# NumPy's main datatype is ndarray
a1 = np.array([1,2,3])
a1

array([1, 2, 3])

In [3]:
type(a1)

numpy.ndarray

In [4]:
a2 = np.array([[1,2,3.3],
              [4,5,6.5]])
a3 = np.array([[[1,2,3],
                [4,5,7],
                [7,8,9]],
              [[10,11,12],
               [13,14,15],
               [16,17,18]]])

In [5]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [6]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  7],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [7]:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [8]:
a1.shape, a2.shape, a3.shape

((3,), (2, 3), (2, 3, 3))

In [9]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int32'), dtype('float64'), dtype('int32'))

In [10]:
a1.size,a2.size, a3.size

(3, 6, 18)

In [11]:
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [12]:
# Create a dataframe from a Numpy array
import pandas as pd
df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.5

# 2. Creating array

In [13]:
sample_array = np.array([1,2,3])
sample_array

array([1, 2, 3])

In [14]:
sample_array.dtype

dtype('int32')

In [17]:
ones = np.ones((2,3))
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [18]:
ones.dtype

dtype('float64')

In [20]:
zeroes = np.zeros((2,3))
zeroes

array([[0., 0., 0.],
       [0., 0., 0.]])

In [23]:
range_array = np.arange(0,10,2)
range_array

array([0, 2, 4, 6, 8])

In [24]:
random_array = np.random.randint(0, 10, size=(3, 5))
random_array

array([[6, 9, 0, 1, 5],
       [4, 8, 1, 6, 7],
       [9, 7, 1, 2, 4]])

In [25]:
random_array2 = np.random.random((5,3))
random_array2

array([[6.07427651e-02, 3.86307637e-01, 3.51921108e-01],
       [1.58692716e-01, 2.24742153e-01, 2.13539623e-01],
       [6.73022606e-01, 6.07611909e-01, 3.54661862e-01],
       [2.64440810e-02, 5.44201633e-01, 4.42898833e-01],
       [6.08121270e-01, 1.87863147e-04, 7.56196701e-01]])

In [27]:
random_array3 = np.random.rand(5,3)
random_array3

array([[0.40315158, 0.16813698, 0.39646759],
       [0.69039358, 0.54031616, 0.96782276],
       [0.40035449, 0.14838181, 0.63071564],
       [0.97998179, 0.46690833, 0.81263292],
       [0.1735702 , 0.72885799, 0.15625173]])

In [33]:
# pseudo-random numbers
np.random.seed(0)
random_array4 = np.random.randint(10, size = (5, 3))
random_array4

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

## 3. Viewing arrays and matrices

In [34]:
np.unique(random_array4)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [35]:
a1

array([1, 2, 3])

In [36]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [37]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  7],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [38]:
a1[0]

1

In [40]:
a2.shape

(2, 3)

In [39]:
a2[0]

array([1. , 2. , 3.3])

In [41]:
a3.shape

(2, 3, 3)

In [42]:
a3[0]

array([[1, 2, 3],
       [4, 5, 7],
       [7, 8, 9]])

In [43]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [44]:
a2[1]

array([4. , 5. , 6.5])

In [47]:
a3.shape

(2, 3, 3)

In [45]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  7],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [46]:
a3[:2, :2, :2]

array([[[ 1,  2],
        [ 4,  5]],

       [[10, 11],
        [13, 14]]])

In [49]:
test_array = np.random.randint(10, size = (5,5,3))
test_array

array([[[9, 9, 0],
        [4, 7, 3],
        [2, 7, 2],
        [0, 0, 4],
        [5, 5, 6]],

       [[8, 4, 1],
        [4, 9, 8],
        [1, 1, 7],
        [9, 9, 3],
        [6, 7, 2]],

       [[0, 3, 5],
        [9, 4, 4],
        [6, 4, 4],
        [3, 4, 4],
        [8, 4, 3]],

       [[7, 5, 5],
        [0, 1, 5],
        [9, 3, 0],
        [5, 0, 1],
        [2, 4, 2]],

       [[0, 3, 2],
        [0, 7, 5],
        [9, 0, 2],
        [7, 2, 9],
        [2, 3, 3]]])

In [51]:
test_array[2,1]

array([9, 4, 4])

In [56]:
test_array[:3,:2,:2]

array([[[9, 9],
        [4, 7]],

       [[8, 4],
        [4, 9]],

       [[0, 3],
        [9, 4]]])

In [59]:
a4 = np.random.randint(10, size = (2,3,4,5))
a4

array([[[[9, 2, 0, 8, 2],
         [7, 8, 4, 4, 1],
         [7, 6, 9, 4, 1],
         [5, 9, 7, 1, 3]],

        [[5, 7, 3, 6, 6],
         [7, 9, 1, 9, 6],
         [0, 3, 8, 4, 1],
         [4, 5, 0, 3, 1]],

        [[4, 4, 4, 0, 0],
         [8, 4, 6, 9, 3],
         [3, 2, 1, 2, 1],
         [3, 4, 1, 1, 0]]],


       [[[7, 8, 4, 3, 5],
         [6, 3, 2, 9, 8],
         [1, 4, 0, 8, 3],
         [9, 5, 5, 1, 7]],

        [[8, 6, 4, 7, 3],
         [5, 3, 6, 4, 7],
         [3, 0, 5, 9, 3],
         [7, 5, 5, 8, 0]],

        [[8, 3, 6, 9, 3],
         [2, 7, 0, 3, 0],
         [3, 6, 1, 9, 2],
         [9, 4, 9, 1, 3]]]])

In [60]:
test_array1 = np.random.randint(10, size=(2,2,2,2))
test_array1

array([[[[2, 4],
         [9, 7]],

        [[4, 9],
         [4, 1]]],


       [[[2, 7],
         [2, 3]],

        [[9, 7],
         [6, 6]]]])

In [61]:
test_array2 = np.random.randint(10, size = (3,2,2,2))
test_array2

array([[[[2, 3],
         [6, 0]],

        [[8, 0],
         [7, 6]]],


       [[[5, 9],
         [6, 5]],

        [[2, 7],
         [1, 9]]],


       [[[2, 2],
         [5, 6]],

        [[4, 2],
         [2, 1]]]])

In [62]:
# from a4 get 4 number of the inner most array
a4

array([[[[9, 2, 0, 8, 2],
         [7, 8, 4, 4, 1],
         [7, 6, 9, 4, 1],
         [5, 9, 7, 1, 3]],

        [[5, 7, 3, 6, 6],
         [7, 9, 1, 9, 6],
         [0, 3, 8, 4, 1],
         [4, 5, 0, 3, 1]],

        [[4, 4, 4, 0, 0],
         [8, 4, 6, 9, 3],
         [3, 2, 1, 2, 1],
         [3, 4, 1, 1, 0]]],


       [[[7, 8, 4, 3, 5],
         [6, 3, 2, 9, 8],
         [1, 4, 0, 8, 3],
         [9, 5, 5, 1, 7]],

        [[8, 6, 4, 7, 3],
         [5, 3, 6, 4, 7],
         [3, 0, 5, 9, 3],
         [7, 5, 5, 8, 0]],

        [[8, 3, 6, 9, 3],
         [2, 7, 0, 3, 0],
         [3, 6, 1, 9, 2],
         [9, 4, 9, 1, 3]]]])

In [67]:
a4[:,:2,:,:4]

array([[[[9, 2, 0, 8],
         [7, 8, 4, 4],
         [7, 6, 9, 4],
         [5, 9, 7, 1]],

        [[5, 7, 3, 6],
         [7, 9, 1, 9],
         [0, 3, 8, 4],
         [4, 5, 0, 3]]],


       [[[7, 8, 4, 3],
         [6, 3, 2, 9],
         [1, 4, 0, 8],
         [9, 5, 5, 1]],

        [[8, 6, 4, 7],
         [5, 3, 6, 4],
         [3, 0, 5, 9],
         [7, 5, 5, 8]]]])

## 4. Manipulating & Comparing array

### Arithmetic

In [69]:
a1
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [70]:
a1

array([1, 2, 3])

In [71]:
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [72]:
a1 + ones

array([[2., 3., 4.],
       [2., 3., 4.]])

In [73]:
ones = np.ones(3)

In [74]:
a1 + ones

array([2., 3., 4.])

In [75]:
a1 - ones

array([0., 1., 2.])

In [76]:
a1 * ones

array([1., 2., 3.])

In [77]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [78]:
a1 *a2

array([[ 1. ,  4. ,  9.9],
       [ 4. , 10. , 19.5]])

In [80]:
# all arithmetic can be performed

In [81]:
a2*a3 # intentionally kept this error(broadcasting)

ValueError: operands could not be broadcast together with shapes (2,3) (2,3,3) 

In [82]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  7],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [83]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [94]:
a2.reshape((3,2))

array([[1. , 2. ],
       [3.3, 4. ],
       [5. , 6.5]])

In [92]:
# floor division
a2 // a1

array([[1., 1., 1.],
       [4., 2., 2.]])

In [93]:
np.square(a2) # numpy has function like add(a,b) etc

array([[ 1.  ,  4.  , 10.89],
       [16.  , 25.  , 42.25]])

In [98]:
x1 = np.arange(9.0).reshape((3, 3))
x2 = np.arange(3.0)

In [99]:
x2

array([0., 1., 2.])

In [100]:
x1

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

In [101]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  7],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [102]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [105]:
a=np.arange(6)
a

array([0, 1, 2, 3, 4, 5])